# Generated by Django 3.2.5 on 2021-08-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lesson',
            field=models.ManyToManyField(help_text='notices selected by a user', to='portale.Lesson'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notice',
            field=models.ManyToManyField(help_text='notices selected by a user', to='portale.Notice'),
        ),
        migrations.AlterField(
            model_name='student',
            name='office_hour',
            field=models.ManyToManyField(help_text='notices selected by a user', to='portale.OfficeHour'),
        ),
    ]
