# Generated by Django 3.2.5 on 2021-08-27 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0002_auto_20210819_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
