# Generated by Django 3.2.5 on 2021-08-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0003_notice_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='data',
            new_name='data_notice',
        ),
    ]
