# Generated by Django 3.2.5 on 2021-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0005_auto_20210831_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='data_lesson',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='data_notice',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='data_officehour',
            field=models.DateField(),
        ),
    ]
